### ISSUE TITLE
🚀 Tasks for 1.1.0 release cycle

### ISSUE THREAD

**Issue by PatrickLaabs** [PatrickLaabs/frigg#87]
## Tasks

* [x] Check Milestone for the specific Release and if everything is completed, or if anything needs to be added or removed.
* [x] Create a new feature-branch for the release-preperation
* [x] Bump Versions in consts Package
* [x] Update go version
* [x] Update go mod
* [x] Update go version for goreleaser
* [x] Update Versions referenced in the README.md
* [x] Test everything :) 
* [x] If everything is fine, push local changes to the prevs. created feature-branch
* [x] merge back to main
* [x] git tag x.x.x && git push --tags
